version: '3.7'

services:
  zookeeper:
    image: bitnami/zookeeper:3.6.0
    ports:
      - 2181:2181
    networks:
      - zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'

  kafka:
    image: bitnami/kafka:2.4.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  zookeeper:
    driver: bridge
